### ISSUE TITLE
Add data export for DBJR

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#118]
[Example Export.xlsx](https://github.com/DBJRdev/ditt-client/files/11198128/Example.Export.xlsx)

Add export for DBJR based on attached file. Differences from what we have in the db need to be discussed here.

**Comment by bedrich-schindler** [comment]
If I look at the example export, I can see it contains more human readable data than the base version. It is because I just exported everything I have in the database. I can imagine this form is more friendly than base version. 

I know that @davidurban told me that this version of export should be only for DBJR instance, but it seem reasonable to have it as default for everybody.

What do you think @davidurban @cencondor?

**Comment by davidurban** [comment]
@bedrich-schindler good idea. Could you please provide sanitised example of new data export? So I can share it with others?

**Comment by davidurban** [comment]
Let's make this the default for everyone and remove the original export.
