### ISSUE TITLE
Allow ending contract in months, that are not closed

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#123]
From Tim/AdB:

> We have encountered one issue with the switch from day-based working hour requirements to the new “contracts“. I just had a meeting with Andrea and Matthias from DBJR to make sure we all have the same expectation.
> 
> Situation is as follows: one person in AdB wants to reduce their weekly working hours, e.g. from 39 to 32. So we thought we change the existing contract, which started 01.07.2022 and give that one an end date. And then we add a new contract for the reduced hours. Yet DITT does not allow to add the end date, as you can see in the screenshot below: when HR department wants to add that the contract ended on 31.05.2023, DITT says that the date cannot be in the past.
> 
> We (DBJR + AdB) understand that changing contracts far to the past would cause trouble, because new months could have been finalized. But the case that will appear very often is that you have to change the contract in the running month for the month before (like in the screenshot), so new months have not been finalized.

![image001](https://github.com/DBJRdev/ditt-client/assets/8739891/63fe5539-02fc-42f4-8945-70db796889ca)

We need to find a way to allow contract termination in month, that is not closed. And trigger re-calculation of that month. 

@bedrich-schindler how complex would it be?

**Comment by bedrich-schindler** [comment]
The logic around contracts is really complex. From my point of with, it did not seem reasonable to change things that already happened. If I change contact (from legal point of view), I expect to make some agreement and then change it, but not in the past. If I allow to terminate contact in the past, complexity of whole system must grow because of extra checks than will have to be made. And I am not sure we (I) will be able to catch all ende-cases if employee or HR do something unexpected. We can try it, but I am unable to give you an estimation until I will try to figure out the way how to do it.

**Comment by davidurban** [comment]
Please allow ending of contract in not finished month.

**Comment by cetcondor** [comment]
@bedrich-schindler Fully understand your point. The reasoning is that organisations have trouble keeping up between talks between boss & employee and then passing that over to HR. (Examples: project grants for employees from EU/foundations etc. often arrive last minute, personal circumstances like taking care of another person require instant reaction, the only HR persons are on holidays or sick)
At least as long a month has not been closed for approval such change needs to be possible.

**Comment by bedrich-schindler** [comment]
I tested it and it should be fine. You can now terminate contact until the work month is marked as "waiting for approval" or as "closed". If the termination should be allowed even if work month (or monthly log) is already marked as waiting for approval, just let me know. Such a change is easy, but this approach is more save and it meets requirement `At least as long a month has not been closed for approval such change needs to be possible.`

With this change, I also slightly refactored add/edit user pages to make it user experience on different screens better:

<img width="698" alt="MOB_1" src="https://github.com/DBJRdev/ditt-client/assets/10213870/36489fc7-9f8e-4d3e-9552-a38c7c9b57d4">
<img width="698" alt="MOB_2" src="https://github.com/DBJRdev/ditt-client/assets/10213870/bd81ba90-a5e5-4913-8b4f-368ccffee0e1">
<img width="2061" alt="DES" src="https://github.com/DBJRdev/ditt-client/assets/10213870/fb458cda-2442-4564-88d5-3fc61210a0ca">

**Comment by davidurban** [comment]
There are minor feedbacks, I think they are worth sorting out:

> 1 Ending a contract - after entering the end date and saving, the overview page does not show the ending date. Only after reload of the page/F5, the ending date appears. It seems that if you do not do a reload, it does not save.
> 2 If you entered a end date of a contract and saved it, and then realized you made a typo (e.g. because May has 31 days and not 30), then you can't edit it anymore. The button is faded out.
> 3 Minor: I wonder why are newly introduced date input fields still defined as <input type="text" … and not as <input type="date" …, because all modern browsers, even Safari, do support the type and offer datepickers automatically?

**Comment by bedrich-schindler** [comment]
So 2  basically means that they require ability to change already terminated contract. It seems quite weird to edit already terminated contract.

Question to @davidurban, I would rather introduce something like "Extend contract" (undo operation for Terminate contract). So if there are no closed months, you can either extend it without end time or enter date when contract would change. It would solve situation when you also want to revert termination.

This approach is quite better from technical point of view as I can prepare special endpoint with set of new validations. This might require some time to implement due to those validations

**Comment by davidurban** [comment]
@bedrich-schindler great idea! Agreed. Please call the function "Make Contract Permanent" or "Change to Permanent Contract". 

It solves the problem and adds flexibility. Please implement.
