### ISSUE TITLE
Sick day should not be an application

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#124]
Sick day should not be an application.

**Comment by davidurban** [comment]
Waiting for response:

https://github.com/DBJRdev/ditt-client/issues/60
https://github.com/DBJRdev/ditt-client/issues/109

**Comment by cetcondor** [comment]
#109 is described as requested.

**Comment by bedrich-schindler** [comment]
@davidurban I am afraid I does not understand the problem. What do you mean by "application"? I checked history of git and there was no change since 2020 in sick days. If I create "sick day" work log, I see it immediately, counted as full work day (2 hours per day is in this case full day). See:

<img width="663" alt="image" src="https://github.com/DBJRdev/ditt-client/assets/10213870/e535bd55-8bd4-45b6-9fd4-d41e9992c389">

<img width="1018" alt="image" src="https://github.com/DBJRdev/ditt-client/assets/10213870/79bfe7fb-8f2e-46b5-b0e3-0e99c959b0e3">

Please, describe the problem so I can fix it.

**Comment by bedrich-schindler** [comment]
The problem is probably email notification with wrong text. We are changing `Antrag auf Krankentag erstellt` to `Krankmeldung `, introduced in #109
