### ISSUE TITLE
Work time is not displayed correctly when there is change in calculation formula

### ISSUE THREAD

**Issue by bedrich-schindler** [DBJRdev/ditt-client#78]
@DBJRdev  @davidurban  I created this isssue to keep track of changes and to explain how will it work. This issue resolves problem with worked time before and after migration that changes calculation formula.

When this issue will be deployed, there will be several variants of monthly log calendar. **Important state is no. 5 that shows how DITT client handles change of calculation formula.**

1. **Open month with no required hours left from previous months**

![S1](https://user-images.githubusercontent.com/10213870/100223653-143c0680-2f1c-11eb-8352-98148d56d0a3.png)
 
2. **Open month with some required hours left from previous months** (can be symbolized with + or -)

![S2](https://user-images.githubusercontent.com/10213870/100223796-42b9e180-2f1c-11eb-9659-c47c1f06f9f9.png)

3. **Month waiting for approval** (can be displayed with or  without required hours left from previous month - see 2)

![S3](https://user-images.githubusercontent.com/10213870/100224129-b360fe00-2f1c-11eb-8f48-3b5b3efbde04.png)

4. **Approved month**

![S4](https://user-images.githubusercontent.com/10213870/100224203-d12e6300-2f1c-11eb-98b0-6f7965a3053b.png)

5. **Approved month where calculated times stored in database and times calculated in javascript client from present work logs differs which means that there was change in calculation formula** - daily totals are therefore hidden to not to confuse users that there is error (like 8:30 vs 8:45 did before) and worked time is taken from database because client uses latest calculation formula

![S5](https://user-images.githubusercontent.com/10213870/100225407-7433ac80-2f1e-11eb-95de-f20604ad6c04.png)

I hope it is OK. Instead of state no.5, there have been message `Total time differs due to changes in calculations` with worked time that are calculated using client, not taken from database (so latest calculation formula was wrongly used) and that confuses people. Data in DB are OK, there is no need to revert migration or something like that.

**Comment by DBJRdev** [comment]
_Daily totals hidden, showing only monthly totals using old calculation formula_
Translation: Angezeigt wird nur die Monatsarbeitszeit nach alter Berechnungsgrundlage. Tagessummen sind ausgeblendet.

Is there a way not to hide the daily totals? Or are they displayed incorrectly (according to new formula) and you can't change that? Showing the old calculation formula in daily totals is not possible?

**Comment by davidurban** [comment]
Thank you for the translation, @bedrich-schindler please add it to the app. 

Unfortunately there is no way to use the old calculation formula. We cannot leave wrong formula in the software (it would be very confusing and complicated), so we "froze" the sums and hid daily total, which we always calculate in browser. 

As we discussed last week, DITT is about to be used by another organisation, this solution of wrong calculations is the cleanest one. In other words is is the smallest "hack" to make sure it works for DBJR's special situation. Others will not need it, since they will use the tool with fixed calculation formula. 

As discussed during the call, @bedrich-schindler please release this version to production, when you have the translation ready.
