### ISSUE TITLE
Improvements of the user management and the displays

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#98]
Change display/display of names as "Last Name, First Name" on some pages, rename column titles, rename (end of month) to (month as number year, e.g. 01/2022), install sorting functions with up and down arrows for some columns.

**Comment by bedrich-schindler** [comment]
Please provide German translations for those titles and exactly which columns to sort.

**Comment by DBJRdev** [comment]
**Change display names in column ‚Name‘ as "Last Name, First Name" on pages:**
- ‚User overview/Nutzer*innen‘
- ‚Special approvals/Anträge‘ and ‚previous applications/frühere Anträge‘
- ‚Employees/Mitarbeitende‘ 

**Question:** for the pages ‚Changes/Veränderungen‘ and ‚Year overview/Jahresübersicht‘
Can the two columns "last name" and first name" be merged into one column, with the display "last name, first name" like on the other pages?

**rename column titles on pages:**
‚User overview/Nutzer*innen‘ 
- column ‚Stand Arbeitszeitkonto‘ to ‚Arbeitszeitkonto‘
- column ‚verplante Urlaubstage‘ to ‚Urlaubskonto‘
- column ‚zeige Einträge‘ to ‚Monatsübersicht‘

‚User profil‘
- title „Urlaubstage“ to „Urlaubskonto“

also rename the wording ‚end of month/Ende Monat‘ to months as numbers and the year
e.g. ‚01/2022‘ (stands for January 2022)
this is on two pages the ‚User overview/Nutzer*innen‘ and ‚Employees/Mitarbeitende‘ > column ‚Arbeitszeitkonto‘

**Sorting functions with up and down arrows on pages:**
- special approvals/Anträge and previous applications/frühere Anträge: columns ‚Name‘ and ‚Typ‘
- Changes/Veränderungen: columns ‚Employee ID/Mitarbeiter-ID‘ and ‚Name‘
- Year overview/Jahresübersicht: columns ‚Employee ID/Mitarbeiter-ID‘ and ‚Name‘

**Comment by cetcondor** [comment]
The German translation change in column ‚verplante Urlaubstage‘ to ‚Urlaubskonto‘ is misleading. Because in order to be understandable, the first number would need to be the remaining vacation days. Currently it's the "planned" ones, which includes the ones that are assigned to concretes dates (past and future).
DBJR will soon give feedback if the change needs to be rolled back or the numbers in the list should be changed. Idea could be instead of 
#planned / #total 
to switch to 
#remaining / #total or all three: #planned / #remaining / #total

**Comment by davidurban** [comment]
Please do not rename the column "verplante Urlaubstage“ to „Urlaubskonto“ per comment above.
